openapi: 3.0.3
info:
    title: Split Expense Microservice
    description: |-
        This is backend Mircroservice for the Split Expense Application
    version: 1.0.0
tags:
    - name: User
paths:
    /users/signup:
        post:
            tags:
                - User
            summary: API for User signup service
            description: This api can be used to add a new user to the system.
            operationId: addUser
            requestBody:
                description: Adds new user to the system
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/userSignUpLoginRequest'
                required: true
            responses:
                '200':
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/userSignUpResponse'
                '400':
                    description: Invalid input
                '422':
                    description: Validation exception
    /users/login:
        post:
            tags:
                - User
            summary: API for User login service
            description: This api can be used to add a new user to the system.
            operationId: loginUser
            requestBody:
                description: Checks whether particular user exists in the system or not
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/userSignUpLoginRequest'
                required: true
            responses:
                '200':
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/userLoginResponse'
                '400':
                    description: Invalid input
                '422':
                    description: Validation exception
    /users/{user_id}/user:
        get:
            operationId: getUser
            security:
                - splitExpenseAuth: []
            parameters:
                - name: authorization
                  in: header
                  required: true
                  schema:
                      type: string
                      minLength: 1
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/getUserResponseSchema'

components:
    securitySchemes:
        splitExpenseAuth:
            type: http
            scheme: bearer
    schemas:
        userSignUpLoginRequest:
            title: User Sign Up/ login Request
            type: object
            required:
                - email
                - password
            properties:
                email:
                    description: Email of the user
                    type: string
                    example: user@gmail.com
                password:
                    description: Password of the user
                    type: string
                    example: Password@123
        userSignUpResponse:
            title: User Sign Up Response
            type: object
            properties:
                message:
                    description: message for the signup/login response
                    type: string
        userLoginResponse:
            title: User Sign Up Response
            type: object
            properties:
                message:
                    description: message for the signup/login response
                    type: string
                accessToken:
                    description: access token for authorization
                    type: string
                refreshToken:
                    description: refreshToken
                    type: string
                expiresIn:
                    description: expiry time for the access token in seconds from the time of generation
                    type: integer
        getUserResponseSchema:
            type: object
            properties:
                user_id:
                    type: integer
                    description: Unique Id of the user
                    example: 10
                email:
                    type: string
                    description: user email id
                    example: johndoe@gmail.com
